//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Common()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int CommonID { get; set; }
        public string Sports { get; set; }
        public string Music { get; set; }
        public string Food { get; set; }
        public string Books { get; set; }
        public string Shows { get; set; }
        public string Movies { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
    }
}
