//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateProject1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class datedbEntities : DbContext
    {
        public datedbEntities()
            : base("name=datedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AgePreference> AgePreferences { get; set; }
        public virtual DbSet<Common> Commons { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Ethnic> Ethnics { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
    }
}
